import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'swiper/css';
import 'swiper/css/pagination';
import Providers from '@/lib/Providers'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Spark Spirit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

 

  return (
    <Providers>
    <html lang="en">
    <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
    </Providers>
  )
}
